import { useMemo, useRef, useState } from "react";
import { Animated, Dimensions, PanResponder, Pressable, StyleSheet, Text, View } from "react-native";
import { Heart, RotateCcw, SlidersHorizontal, Star } from "lucide-react-native";
import { router } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { MediaBadge, MediaCover } from "../../components/media-card";

const cards=[
  {id:"meera",name:"Meera Shah",meta:"30 · Financial Analyst · Pune",score:"79%",prompt:"I value independence, direct conversations and people who keep their word.",media:[{kind:"image" as const,src:"https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=700&q=80"}]},
  {id:"isha",name:"Isha Kapoor",meta:"27 · Clinical Psychologist · Delhi",score:"76%",prompt:"A green flag I bring: I ask questions before I make assumptions.",media:[{kind:"image" as const,src:"https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=700&q=80"}]},
  {id:"ananya",name:"Ananya Rao",meta:"29 · Product Designer · Bengaluru",score:"92%",prompt:"A small joy I never get tired of: finding a new walking route and a good bookshop.",media:[{kind:"image" as const,src:"https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=700&q=80"}]},
];

export default function Discover(){
  const insets=useSafeAreaInsets();
  const [index,setIndex]=useState(0); const [feedback,setFeedback]=useState(""); const [filtersOpen,setFiltersOpen]=useState(false); const [activeFilter,setActiveFilter]=useState("Verified only");
  const position=useRef(new Animated.ValueXY()).current; const width=Dimensions.get("window").width;
  const current=cards[index%cards.length]; const nextCard=cards[(index+1)%cards.length];
  const advance=(action:"pass"|"save"|"interest")=>{const copy=action==="interest"?`Interest sent to ${current.name}`:action==="save"?`${current.name} saved to shortlist`:"We’ll tune your next picks";setFeedback(copy);setIndex(value=>(value+1)%cards.length);position.setValue({x:0,y:0});};
  const swipe=(dx:number,action:"pass"|"interest")=>{Animated.timing(position,{toValue:{x:dx>0?width*1.4:-width*1.4,y:0},duration:220,useNativeDriver:true}).start(()=>advance(action));};
  const panResponder=useMemo(()=>PanResponder.create({onMoveShouldSetPanResponder:(_,g)=>Math.abs(g.dx)>12&&Math.abs(g.dx)>Math.abs(g.dy),onPanResponderMove:Animated.event([null,{dx:position.x,dy:position.y}],{useNativeDriver:false}),onPanResponderRelease:(_,g)=>{if(Math.abs(g.dx)>100)swipe(g.dx,g.dx>0?"interest":"pass");else Animated.spring(position,{toValue:{x:0,y:0},useNativeDriver:true,bounciness:8}).start();}}),[position]);
  const rotation=position.x.interpolate({inputRange:[-width/2,0,width/2],outputRange:["-8deg","0deg","8deg"]});
  return <View style={[s.screen,{paddingTop:insets.top}]}><View style={s.top}><View><Text style={s.kicker}>DISCOVER</Text><Text style={s.title}>People with intention</Text></View><Pressable style={s.filter} onPress={()=>setFiltersOpen(!filtersOpen)} accessibilityRole="button" accessibilityLabel="Open discovery filters"><SlidersHorizontal size={17} color="#6D46E8"/></Pressable></View><View style={s.chips}><Pressable onPress={()=>setActiveFilter(activeFilter==="Verified only"?"All profiles":"Verified only")}><Text style={[s.chip,activeFilter==="Verified only"&&s.chipActive]}>{activeFilter}</Text></Pressable><Pressable><Text style={s.chip}>26–34</Text></Pressable><Pressable><Text style={s.chip}>Bengaluru + nearby</Text></Pressable></View>{filtersOpen&&<View style={s.filters}><Text style={s.filterTitle}>Quick filters</Text><Text style={s.filterCopy}>Age, location, education and privacy preferences can be expanded here.</Text><Pressable style={s.filterButton} onPress={()=>setFiltersOpen(false)}><Text style={s.filterButtonText}>Done</Text></Pressable></View>}<View style={s.deckHeader}><Text style={s.deckLabel}>TODAY'S THOUGHTFUL PICKS</Text><Text style={s.deckCount}>{index+1} / {cards.length}</Text></View><View style={s.deck}>{<View style={[s.deckCard,s.peekCard]}><MediaCover media={nextCard.media[0]} style={s.deckPhoto}/></View>}<Animated.View {...panResponder.panHandlers} style={[s.deckCard,{transform:[{translateX:position.x},{translateY:position.y},{rotate:rotation}]}]}><MediaCover media={current.media[0]} style={s.deckPhoto}/><MediaBadge hasVideo={current.media.some(item=>item.kind==="video")}/><View style={s.deckBody}><View style={s.deckHeading}><View><Text style={s.name}>{current.name}</Text><Text style={s.meta}>{current.meta}</Text></View><Text style={s.score}>{current.score}</Text></View><View style={s.prompt}><Text style={s.promptKicker}>A LITTLE MORE ABOUT THEM</Text><Text style={s.promptText}>“{current.prompt}”</Text></View><View style={s.actionRow}><Pressable style={s.pass} onPress={()=>advance("pass")} accessibilityLabel="Pass profile"><RotateCcw size={17} color="#687188"/></Pressable><Pressable style={s.save} onPress={()=>advance("save")} accessibilityLabel="Shortlist profile"><Star size={17} color="#6D46E8"/></Pressable><Pressable style={s.interest} onPress={()=>advance("interest")} accessibilityLabel="Send interest"><Heart size={16} color="#fff" fill="#fff"/><Text style={s.interestText}>Send interest</Text></Pressable></View></View></Animated.View></View>{feedback&&<View style={s.feedback}><Text style={s.feedbackText}>{feedback}</Text></View>}<Text style={s.swipeHint}>Swipe left to pass · right to send interest · tap actions for control</Text></View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:"#FCFBF9",paddingHorizontal:20},top:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:19},kicker:{fontSize:9,fontWeight:"700",letterSpacing:1.3,color:"#8A91A1"},title:{fontSize:21,fontWeight:"700",color:"#18233D",marginTop:6},filter:{width:42,height:42,borderRadius:13,borderWidth:1,borderColor:"#E7E8F0",alignItems:"center",justifyContent:"center",backgroundColor:"#fff"},chips:{flexDirection:"row",gap:7,marginBottom:15},chip:{fontSize:10,color:"#6D46E8",backgroundColor:"#F3F1FF",paddingVertical:8,paddingHorizontal:10,borderRadius:8},chipActive:{backgroundColor:"#E7F7F2",color:"#168B82"},filters:{padding:14,borderRadius:13,borderWidth:1,borderColor:"#DCD6F6",backgroundColor:"#FBFAFF",marginBottom:15},filterTitle:{fontSize:12,fontWeight:"700",color:"#18233D"},filterCopy:{fontSize:10,color:"#687188",lineHeight:15,marginTop:5},filterButton:{alignSelf:"flex-start",marginTop:10,paddingVertical:7,paddingHorizontal:12,borderRadius:8,backgroundColor:"#6D46E8"},filterButtonText:{fontSize:10,fontWeight:"700",color:"#fff"},deckHeader:{flexDirection:"row",justifyContent:"space-between",marginBottom:10},deckLabel:{fontSize:9,fontWeight:"700",letterSpacing:1.2,color:"#8A91A1"},deckCount:{fontSize:10,color:"#6D46E8",fontWeight:"700"},deck:{height:510,position:"relative"},deckCard:{position:"absolute",left:0,right:0,top:0,bottom:0,overflow:"hidden",borderRadius:19,borderWidth:1,borderColor:"#E7E8F0",backgroundColor:"#fff",shadowColor:"#18233D",shadowOpacity:.12,shadowRadius:18,shadowOffset:{width:0,height:9},elevation:5},peekCard:{transform:[{scale:.96},{translateY:10}],opacity:.55},deckPhoto:{width:"100%",height:285},deckBody:{padding:16},deckHeading:{flexDirection:"row",justifyContent:"space-between",gap:10},name:{fontSize:17,fontWeight:"700",color:"#18233D"},score:{fontSize:15,fontWeight:"700",color:"#168B82"},meta:{fontSize:11,color:"#687188",marginTop:5},prompt:{padding:12,marginTop:16,borderRadius:11,backgroundColor:"#F7F5FF"},promptKicker:{fontSize:9,fontWeight:"700",letterSpacing:.7,color:"#6D46E8"},promptText:{fontSize:11,lineHeight:17,color:"#18233D",marginTop:6},actionRow:{flexDirection:"row",gap:8,marginTop:18},pass:{height:43,width:43,borderRadius:11,borderWidth:1,borderColor:"#E7E8F0",alignItems:"center",justifyContent:"center"},save:{height:43,width:43,borderRadius:11,backgroundColor:"#F3F1FF",alignItems:"center",justifyContent:"center"},interest:{height:43,flex:1,borderRadius:11,backgroundColor:"#6D46E8",alignItems:"center",justifyContent:"center",flexDirection:"row",gap:7},interestText:{color:"#fff",fontSize:11,fontWeight:"700"},feedback:{alignSelf:"center",marginTop:10,paddingVertical:7,paddingHorizontal:12,borderRadius:10,backgroundColor:"#E7F7F2"},feedbackText:{fontSize:10,color:"#168B82",fontWeight:"700"},swipeHint:{textAlign:"center",fontSize:10,color:"#8A91A1",marginTop:10,marginBottom:10}});
