import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Globe2, LockKeyhole, ShieldCheck } from "lucide-react-native";
import { useLanguage } from "../../lib/language";
import { theme } from "../../lib/theme";

export default function Profile(){
  const { language, setLanguage, t } = useLanguage();
  return <ScrollView style={s.screen} contentContainerStyle={{padding:20}}><Text style={s.kicker}>{t("yourProfile")}</Text><Text style={s.title}>Ananya Rao</Text><Text style={s.meta}>Product Designer · Bengaluru</Text><View style={s.card}><View style={s.row}><ShieldCheck size={20} color="#168B82"/><View><Text style={s.strong}>{t("identityVerified")}</Text><Text style={s.copy}>{t("identityCopy")}</Text></View></View><View style={s.row}><LockKeyhole size={20} color={theme.red}/><View><Text style={s.strong}>{t("privacyControls")}</Text><Text style={s.copy}>{t("privacyCopy")}</Text></View></View><View style={[s.row,s.lastRow]}><Globe2 size={20} color={theme.red}/><View style={s.languageCopy}><Text style={s.strong}>{t("language")}</Text><Text style={s.copy}>{language === "en" ? t("englishIndia") : t("kannada")}</Text><View style={s.languageOptions}><Pressable onPress={() => setLanguage("en")} accessibilityRole="button" accessibilityState={{selected:language === "en"}} style={[s.languageOption,language === "en" && s.languageOptionActive]}><Text style={[s.languageOptionText,language === "en" && s.languageOptionActiveText]}>English</Text></Pressable><Pressable onPress={() => setLanguage("kn")} accessibilityRole="button" accessibilityState={{selected:language === "kn"}} style={[s.languageOption,language === "kn" && s.languageOptionActive]}><Text style={[s.languageOptionText,language === "kn" && s.languageOptionActiveText]}>ಕನ್ನಡ</Text></Pressable></View></View></View></View></ScrollView>
}

const s=StyleSheet.create({screen:{flex:1,backgroundColor:theme.background},kicker:{fontSize:9,fontWeight:"700",letterSpacing:1.3,color:"#8A91A1"},title:{fontSize:26,fontWeight:"700",color:theme.ink,marginTop:6},meta:{fontSize:12,color:theme.muted,marginTop:6},card:{backgroundColor:"#fff",borderWidth:1,borderColor:theme.border,borderRadius:20,padding:18,marginTop:30,shadowColor:theme.redDeep,shadowOpacity:.06,shadowRadius:14,shadowOffset:{width:0,height:8},elevation:3},row:{flexDirection:"row",gap:12,alignItems:"flex-start",paddingVertical:15,borderBottomWidth:1,borderBottomColor:"#F0F1F5"},lastRow:{borderBottomWidth:0,paddingBottom:3},strong:{fontSize:13,fontWeight:"700",color:theme.ink},copy:{fontSize:11,lineHeight:16,color:theme.muted,marginTop:4},languageCopy:{flex:1},languageOptions:{flexDirection:"row",gap:6,marginTop:10},languageOption:{paddingVertical:7,paddingHorizontal:11,borderRadius:8,borderWidth:1,borderColor:"#E1DEEF",backgroundColor:"#fff"},languageOptionActive:{borderColor:theme.red,backgroundColor:theme.redSoft},languageOptionText:{fontSize:10,fontWeight:"700",color:theme.muted},languageOptionActiveText:{color:theme.red}});
