import { useState } from "react";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { ArrowLeft, Check, Heart, LockKeyhole, MessageCircle, ShieldCheck, Star } from "lucide-react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { MediaBadge, MediaCover } from "../../components/media-card";
import { useLanguage } from "../../lib/language";
import { theme } from "../../lib/theme";

const profileMap={
  rhea:{name:"Rhea Menon",age:"31",meta:"Architect · Mumbai",score:"88%",about:"An architect with a soft spot for old cities, strong coffee and building a warm home filled with books.",media:[{kind:"image" as const,src:"https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=85"},{kind:"image" as const,src:"https://images.unsplash.com/photo-1546961342-ea5f68f2f7dc?auto=format&fit=crop&w=800&q=85"}]},
  ananya:{name:"Ananya Rao",age:"29",meta:"Product Designer · Bengaluru",score:"92%",about:"Curious, kind and quietly ambitious. I enjoy long walks, thoughtful conversations and making space for people to be themselves.",media:[{kind:"image" as const,src:"https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=85"},{kind:"image" as const,src:"https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=85"}]},
};
export default function ProfileDetail(){const insets=useSafeAreaInsets();const {t}=useLanguage();const{id}=useLocalSearchParams<{id?:string}>();const profile=profileMap[id as keyof typeof profileMap]||profileMap.rhea;const[selected,setSelected]=useState(0);const[sent,setSent]=useState(false);const[saved,setSaved]=useState(false);const[requested,setRequested]=useState(false);return <ScrollView style={s.screen} contentContainerStyle={{paddingBottom:insets.bottom+35}}><Pressable onPress={()=>router.back()} style={[s.back,{paddingTop:insets.top+14}]}><ArrowLeft size={18} color={theme.ink}/><Text style={s.backText}>{t("backDiscover")}</Text></Pressable><View style={s.mediaBox}><MediaCover media={profile.media[selected]} style={s.image}/><MediaBadge hasVideo={profile.media.some(item=>item.kind==="video")}/></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.thumbs}>{profile.media.map((item,index)=><Pressable key={`${item.src}-${index}`} onPress={()=>setSelected(index)} style={[s.thumb,selected===index&&s.thumbActive]} accessibilityLabel={`${t("viewMedia")} ${index+1}`}><Image source={{uri:item.src}} style={StyleSheet.absoluteFill}/></Pressable>)}</ScrollView><View style={s.body}><View style={s.row}><View><Text style={s.kicker}>{t("preferenceMatch")}</Text><Text style={s.title}>{profile.name}, {profile.age}</Text><Text style={s.meta}>{profile.meta}</Text></View><Text style={s.score}>{profile.score}</Text></View><Text style={s.about}>{profile.about}</Text><View style={s.tags}><Text style={s.tag}>{t("verified")}</Text><Text style={s.tag}>{t("privacyControlled")}</Text><Text style={s.tag}>{t("preferenceMatch")}</Text></View><View style={s.actions}><Pressable style={s.interest} onPress={()=>setSent(!sent)}><Heart size={16} color="#fff" fill={sent?"#fff":"none"}/><Text style={s.white}>{sent?t("interestSent"):t("sendInterest")}</Text></Pressable><Pressable style={s.save} onPress={()=>setSaved(!saved)} accessibilityLabel={t("shortlistProfile")}><Star size={17} color={theme.red} fill={saved?theme.red:"none"}/></Pressable><Pressable style={s.save} onPress={()=>router.push("/(tabs)/messages")} accessibilityLabel={t("messageProfile")}><MessageCircle size={17} color={theme.red}/></Pressable></View><Pressable style={s.private} onPress={()=>setRequested(!requested)}><LockKeyhole size={17} color={theme.red}/><View style={{flex:1}}><Text style={s.strong}>{requested?t("photoRequestSent"):t("requestPhotos")}</Text><Text style={s.privateText}>{t("shareCopy")}</Text></View><Check size={15} color="#168B82"/></Pressable><View style={s.note}><ShieldCheck size={16} color="#168B82"/><Text style={s.privateText}>{t("mediaPrivacy")}</Text></View></View></ScrollView>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:theme.background},back:{flexDirection:"row",alignItems:"center",gap:7,paddingHorizontal:20,paddingBottom:14},backText:{fontSize:12,color:theme.ink,fontWeight:"600"},mediaBox:{height:430,overflow:"hidden",backgroundColor:"#EAE8F2"},image:{width:"100%",height:430},thumbs:{gap:8,paddingHorizontal:20,paddingVertical:12},thumb:{width:56,height:56,overflow:"hidden",borderRadius:9,borderWidth:2,borderColor:"transparent"},thumbActive:{borderColor:theme.red},body:{padding:20},row:{flexDirection:"row",justifyContent:"space-between",gap:12},kicker:{fontSize:9,fontWeight:"700",letterSpacing:1.3,color:"#8A91A1"},title:{fontSize:26,fontWeight:"700",color:theme.ink,marginTop:7},meta:{fontSize:12,color:theme.muted,marginTop:5},score:{fontSize:23,fontWeight:"700",color:"#168B82"},about:{fontSize:13,lineHeight:21,color:theme.muted,marginTop:22},tags:{flexDirection:"row",gap:7,marginTop:18,flexWrap:"wrap"},tag:{fontSize:10,color:theme.muted,backgroundColor:"#F1F1F6",paddingVertical:7,paddingHorizontal:9,borderRadius:7},actions:{flexDirection:"row",gap:9,marginTop:28},interest:{height:46,borderRadius:12,backgroundColor:theme.red,flex:1,alignItems:"center",justifyContent:"center",flexDirection:"row",gap:7},white:{color:"#fff",fontWeight:"700",fontSize:12},save:{height:46,width:46,borderRadius:12,backgroundColor:theme.redSoft,alignItems:"center",justifyContent:"center"},private:{flexDirection:"row",gap:10,alignItems:"center",marginTop:18,padding:14,borderRadius:13,backgroundColor:theme.redSoft},strong:{fontSize:12,fontWeight:"700",color:theme.ink},privateText:{fontSize:11,lineHeight:16,color:theme.muted,marginTop:4},note:{flexDirection:"row",gap:8,alignItems:"center",marginTop:23}});
