"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, Check, ChevronRight, Heart, LockKeyhole, MessageCircle, Search, ShieldCheck, Sparkles, Star, Users, Wifi } from "lucide-react";
import { PublicNav } from "@/components/public-nav";
import { Brand, ProfileCard } from "@/components/ui";
import { MediaMatchSection, EngagementLoop } from "@/components/media-experience";
import { profiles } from "@/lib/mock-data";

function Intro() { const [visible, setVisible] = useState(false); useEffect(() => { if (sessionStorage.getItem("advaita-intro-seen")) return; sessionStorage.setItem("advaita-intro-seen", "1"); setVisible(true); const timer = window.setTimeout(() => setVisible(false), 1700); return () => window.clearTimeout(timer); }, []); if (!visible) return null; return <div className="intro" aria-hidden="true"><div className="intro-inner"><div className="intro-symbol" /><div className="intro-word">Advaita Matrimony</div><span style={{ fontSize:11, color:"#aeb4cb" }}>Meaningful connections. Built on trust.</span></div></div>; }

export default function Home() {
  return <><Intro /><PublicNav /><main>
    <section className="hero"><div className="container hero-grid"><motion.div className="hero-copy" initial={{ opacity:0, y:20 }} animate={{ opacity:1, y:0 }} transition={{ duration:.7, delay:.2 }}><span className="eyebrow">A new kind of matrimony</span><h1>Find someone who understands <em>your journey.</em></h1><p>A trusted and inclusive matrimony platform designed for meaningful relationships — with privacy, intention and a little more humanity.</p><div className="hero-ctas"><Link className="btn btn-primary" href="/onboarding">Create your profile <ArrowRight size={16} /></Link><Link className="btn btn-ghost" href="/discover"><Search size={16} /> Explore matches</Link></div><div className="hero-note"><ShieldCheck size={15} /> Verified profiles · Privacy-first by design</div></motion.div><div className="hero-art" aria-label="A selection of verified profiles"><div className="hero-orb" /><div className="hero-line" /><div className="hero-sticker sticker-one"><ShieldCheck size={16} /> Identity verified</div><div className="hero-sticker sticker-two"><Sparkles size={16} color="var(--rose)" /> 92% preference match</div><motion.div className="hero-card hero-card-main" initial={{ opacity:0, scale:.9, rotate:-12 }} animate={{ opacity:1, scale:1, rotate:-7 }} transition={{ duration:.7, delay:.4 }}><img src={profiles[0].image} alt="Ananya, a verified member" /><span className="pill pill-verified hero-card-tag"><span className="dot" /> Active now</span><div className="hero-card-content"><strong>Ananya Rao, 29</strong><small>Product Designer · Bengaluru</small></div></motion.div><motion.div className="hero-card hero-card-side" initial={{ opacity:0, scale:.9, rotate:14 }} animate={{ opacity:1, scale:1, rotate:8 }} transition={{ duration:.7, delay:.65 }}><img src={profiles[1].image} alt="Rhea, a verified member" /><div className="hero-card-content"><strong>Rhea Menon, 31</strong><small>Architect · Mumbai</small></div></motion.div></div></div></section>
    <section className="trust-strip"><div className="container trust-grid"><Trust icon={<ShieldCheck />} title="Verified profiles" body="Identity-led trust" /><Trust icon={<LockKeyhole />} title="Privacy protected" body="You choose what to share" /><Trust icon={<Users />} title="Inclusive by design" body="Every journey belongs" /><Trust icon={<MessageCircle />} title="Secure communication" body="Connect at your pace" /></div></section>
    <section className="section" id="how-it-works"><div className="container"><div className="section-head"><span className="eyebrow">A considered beginning</span><h2>Built for the relationship you’re ready for.</h2><p>Everything on Advaita is designed to make meeting someone feel more thoughtful — from your first preference to your first conversation.</p></div><div className="steps"><Step n="01" title="Create your profile" text="Share the parts of your life that matter to you." /><Step n="02" title="Set preferences" text="Tell us what a meaningful fit looks like." /><Step n="03" title="Get verified" text="Build confidence with a trusted profile." /><Step n="04" title="Discover matches" text="Explore people aligned with your journey." /><Step n="05" title="Connect securely" text="Take the next step on your terms." /></div></div></section>
    <section className="section cream"><div className="container"><div className="section-head"><span className="eyebrow">Trust is personal</span><h2>Thoughtful tools for a more human search.</h2></div><div className="feature-grid"><Feature icon={<LockKeyhole />} title="Controlled photo access" text="Keep private photos protected and share them only when it feels right." /><Feature icon={<Search />} title="Preference matching" text="See why a profile fits based on the preferences you chose." /><Feature icon={<Wifi />} title="Real-time visibility" text="Know when someone is active, while staying in control of your own presence." /><Feature icon={<ShieldCheck />} title="A safety-first space" text="Clear reporting, blocking and guidance at every step." /></div></div></section>
    <section className="section inclusive"><div className="container inclusive-grid"><div className="section-head"><span className="eyebrow">Everyone belongs here</span><h2>A wider definition of connection.</h2><p>Advaita is built to honour different lives, identities and experiences — without putting anyone in a separate box.</p><Link href="/about" className="btn btn-soft" style={{ marginTop:24 }}>Our inclusive promise <ArrowRight size={16} /></Link></div><div className="inclusive-list"><Inclusive title="General matrimony" text="For people looking for a grounded, lasting partnership." /><Inclusive title="Physical & locomotor" text="A respectful space where access needs are part of the conversation." /><Inclusive title="Hearing & speech" text="Connection that makes room for different ways of communicating." /><Inclusive title="Vitiligo & skin conditions" text="Profiles that lead with the whole person, not a label." /></div></div></section>
    <MediaMatchSection profiles={profiles.slice(0,4)} />
    <section className="section"><div className="container"><div className="section-head" style={{ display:"flex", justifyContent:"space-between", maxWidth:"none", alignItems:"end", gap:20 }}><div><span className="eyebrow">Meet with intention</span><h2>People, not profiles.</h2><p>Browse a small selection of verified members from our community.</p></div><Link href="/discover" className="nav-link">View all matches <ChevronRight size={14} style={{ verticalAlign:"middle" }} /></Link></div><div className="profile-grid">{profiles.slice(0,4).map(profile => <ProfileCard key={profile.id} profile={profile} />)}</div></div></section>
    <EngagementLoop />
    <section className="section lavender"><div className="container"><div className="cta-panel"><div><span className="eyebrow">Your next chapter can start here</span><h2>Make space for something meaningful.</h2><p>Join a community that chooses trust, clarity and real connection.</p></div><Link className="btn btn-primary" href="/onboarding">Create your profile <ArrowRight size={16} /></Link></div></div></section>
  </main><Footer /></>;
}
function Trust({ icon, title, body }: { icon: React.ReactNode; title: string; body: string }) { return <div className="trust-item">{icon}<div><strong>{title}</strong><span>{body}</span></div></div>; }
function Feature({ icon, title, text }: { icon: React.ReactNode; title:string; text:string }) { return <motion.div className="feature-card" whileInView={{ opacity:1, y:0 }} initial={{ opacity:0, y:15 }} viewport={{ once:true }}><span className="feature-icon">{icon}</span><h3>{title}</h3><p>{text}</p></motion.div>; }
function Step({ n, title, text }: { n:string; title:string; text:string }) { return <div className="step"><div className="step-number">{n}</div><h3>{title}</h3><p>{text}</p></div>; }
function Inclusive({ title, text }: { title:string; text:string }) { return <div className="inclusive-item"><strong>{title}</strong><span>{text}</span></div>; }
function Footer() { return <footer className="footer"><div className="container"><div className="footer-grid"><div><Brand /><p className="footer-copy">Meaningful connections, built on trust. A modern, inclusive matrimony experience for people who are ready for something real.</p></div><div><h4>Explore</h4><Link href="/discover">Discover</Link><Link href="/membership">Membership</Link><Link href="/about">About us</Link></div><div><h4>Trust & safety</h4><Link href="/safety">Safety center</Link><Link href="/privacy">Privacy policy</Link><Link href="/terms">Terms of use</Link></div><div><h4>Need help?</h4><Link href="/faq">FAQs</Link><Link href="/contact">Contact support</Link><Link href="/login">Member login</Link></div></div><div className="footer-bottom"><span>© 2026 Advaita Matrimony. Frontend preview.</span><span>Made with care for meaningful beginnings.</span></div></div></footer>; }
