"use client";

import Link from "next/link";
import { ArrowRight, Bell, Check, Eye, Heart, ShieldCheck, Star, UserRound } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { ProfileCard } from "@/components/ui";
import { profiles } from "@/lib/mock-data";

export default function Dashboard() { return <AppShell><div className="dashboard-hero"><div><span className="eyebrow" style={{ color:"#d9c9ff" }}>Your space is taking shape</span><h2>Your matches are getting better.</h2><p>12 new compatible profiles were added today.</p></div><div className="completion"><div className="progress-ring"><strong>86%</strong></div><div><span>Profile strength</span><Link href="/app/profile" style={{ color:"#fff", fontSize:12, fontWeight:700, display:"block", marginTop:5 }}>Improve profile <ArrowRight size={13} style={{ verticalAlign:"middle" }} /></Link></div></div></div><div className="dashboard-grid"><div><div className="content-heading"><h2>Recommended for you</h2><Link href="/app/discover">See all</Link></div><div className="recommend-grid">{profiles.slice(0,3).map(profile => <ProfileCard key={profile.id} profile={profile} compact />)}</div><div style={{ marginTop:30 }}><div className="content-heading"><h2>Your recent activity</h2><Link href="/app/interests">View interests</Link></div><div className="side-card"><Activity icon={<Heart size={15} />} title="Arjun Nair sent you an interest" text="Take a look at his profile when you have a moment." time="12 min ago" /><Activity icon={<Eye size={15} />} title="Your profile was viewed 4 times" text="Your profile is getting noticed in Bengaluru." time="Today" /><Activity icon={<ShieldCheck size={15} />} title="Profile verification complete" text="Your verified badge is now visible to members." time="Yesterday" /></div></div></div><aside className="side-stack"><div className="side-card"><div style={{ display:"flex", justifyContent:"space-between", alignItems:"start" }}><div><h3>Profile strength</h3><p>Add two more details to improve your recommendations.</p></div><strong style={{ color:"var(--plum)", fontSize:18 }}>86%</strong></div><div className="side-progress"><span /></div><Link className="btn btn-soft" href="/app/profile" style={{ width:"100%", minHeight:38, fontSize:12 }}>Complete profile</Link></div><div className="side-card"><h3>Quick actions</h3><Link className="app-link" style={{ padding: "10px 0" }} href="/app/discover"><Star size={16} /> Explore new profiles</Link><Link className="app-link" style={{ padding: "10px 0" }} href="/app/notifications"><Bell size={16} /> View notifications <span className="pill pill-premium" style={{ marginLeft:"auto", padding:"3px 6px" }}>2</span></Link><Link className="app-link" style={{ padding: "10px 0" }} href="/app/settings"><UserRound size={16} /> Privacy controls</Link></div></aside></div></AppShell>; }
function Activity({ icon, title, text, time }: { icon:React.ReactNode; title:string; text:string; time:string }) { return <div className="activity-item"><span className="activity-icon">{icon}</span><div style={{ flex:1 }}><strong>{title}</strong><span>{text}</span></div><span style={{ color:"#a0a6b5", fontSize:10 }}>{time}</span></div>; }
