"use client";

import Link from "next/link";
import { Bell, Compass, Heart, Home, LogOut, Menu, MessageCircle, Search, Settings, ShieldCheck, Star, UserRound, Users, X } from "lucide-react";
import { useState } from "react";
import { Brand, PremiumBadge } from "./ui";

const links = [{ href:"/app", label:"Home", icon:Home },{ href:"/app/discover", label:"Discover", icon:Compass },{ href:"/app/matches", label:"Matches", icon:Users },{ href:"/app/interests", label:"Interests", icon:Heart },{ href:"/app/shortlist", label:"Shortlisted", icon:Star },{ href:"/app/messages", label:"Messages", icon:MessageCircle },{ href:"/app/viewed", label:"Who viewed me", icon:UserRound }];

export function AppShell({ children, active = "Home" }: { children: React.ReactNode; active?: string }) {
  const [mobileOpen, setMobileOpen] = useState(false);
  return <div className="app-shell"><aside className={mobileOpen ? "app-nav app-nav-open" : "app-nav"}><div style={{ display:"flex", justifyContent:"space-between", alignItems:"center" }}><Brand /><button className="icon-btn mobile-menu" onClick={() => setMobileOpen(false)} aria-label="Close navigation"><X size={18} /></button></div><div className="app-nav-section">Your space</div>{links.map(({ href,label,icon:Icon }) => <Link key={href} href={href} className={`app-link ${active === label ? "active" : ""}`} onClick={() => setMobileOpen(false)}><Icon /> {label}</Link>)}<div className="app-nav-section" style={{ marginTop:18 }}>Account</div><Link href="/app/profile" className="app-link"><UserRound /> My profile</Link><Link href="/app/settings" className="app-link"><Settings /> Settings</Link><Link href="/safety" className="app-link"><ShieldCheck /> Safety center</Link><div className="app-user"><img className="avatar" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100&q=80" alt="Ananya Rao" /><div className="avatar-copy"><strong>Ananya Rao</strong><span><PremiumBadge /></span></div></div></aside>{mobileOpen && <button aria-label="Close navigation overlay" onClick={() => setMobileOpen(false)} style={{ position:"fixed", inset:0, zIndex:19, background:"rgba(24,35,61,.3)", border:0 }} /> }<main className="app-main"><div className="app-topbar"><div><button className="icon-btn mobile-menu" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu size={18} /></button><h1 style={{ display:"inline", marginLeft:10 }}>{active === "Home" ? "Good morning, Ananya" : active}</h1><p style={{ marginLeft:48 }}>{active === "Home" ? "We found 14 profiles matching your preferences today." : "Take your time. Meaningful connections have no shortcuts."}</p></div><div className="top-actions"><button className="icon-btn" aria-label="Search"><Search size={17} /></button><Link href="/app/notifications" className="icon-btn" aria-label="Notifications"><Bell size={17} /></Link><img className="avatar" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100&q=80" alt="Your profile" /></div></div>{children}</main><nav className="mobile-tabs" aria-label="Mobile navigation">{links.slice(0,5).map(({href,label,icon:Icon}) => <Link key={href} href={href} className={active === label ? "active" : ""}><Icon size={18} /><span>{label}</span></Link>)}</nav></div>;
}
