export type SupportedLanguage = "en" | "kn";

/** Exact UI copy translations used by the full-site language runtime. */
export const uiTranslations: Record<string, string> = {
  "Loading": "ಲೋಡ್ ಆಗುತ್ತಿದೆ",
  "Advaita Matrimony home": "Advaita Matrimony ಮುಖಪುಟ",
  "Dismiss notification": "ಅಧಿಸೂಚನೆ ಮುಚ್ಚಿ",
  "Pause profile intro": "ಪ್ರೊಫೈಲ್ ಪರಿಚಯ ವಿರಾಮಗೊಳಿಸಿ",
  "Play profile intro": "ಪ್ರೊಫೈಲ್ ಪರಿಚಯ ಪ್ಲೇ ಮಾಡಿ",
  "Video intro": "ವೀಡಿಯೊ ಪರಿಚಯ",
  "Password, login sessions and account recovery": "ಪಾಸ್‌ವರ್ಡ್, ಲಾಗಿನ್ ಸೆಷನ್‌ಗಳು ಮತ್ತು ಖಾತೆ ಮರುಪಡೆಯುವಿಕೆ",
  "Who can find you and view your photos": "ಯಾರು ನಿಮ್ಮನ್ನು ಹುಡುಕಬಹುದು ಮತ್ತು ನಿಮ್ಮ ಫೋಟೋಗಳನ್ನು ನೋಡಬಹುದು",
  "Choose what you hear about": "ಯಾವ ಅಧಿಸೂಚನೆಗಳನ್ನು ಪಡೆಯಬೇಕು ಎಂದು ಆಯ್ಕೆಮಾಡಿ",
  "Manage members you’ve blocked": "ನೀವು ನಿರ್ಬಂಧಿಸಿದ ಸದಸ್ಯರನ್ನು ನಿರ್ವಹಿಸಿ",
  "A selection of verified profiles": "ಪರಿಶೀಲಿತ ಪ್ರೊಫೈಲ್‌ಗಳ ಆಯ್ಕೆ",
  "Set preferences": "ಆದ್ಯತೆಗಳನ್ನು ಹೊಂದಿಸಿ",
  "Get verified": "ಪರಿಶೀಲನೆ ಪಡೆಯಿರಿ",
  "Discover matches": "ಹೊಂದಾಣಿಕೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
  "Connect securely": "ಸುರಕ್ಷಿತವಾಗಿ ಸಂಪರ್ಕಿಸಿ",
  "Meaningful connections, built on trust. A modern, inclusive matrimony experience for people who are ready for something real.": "ವಿಶ್ವಾಸದ ಮೇಲೆ ನಿರ್ಮಿತ ಅರ್ಥಪೂರ್ಣ ಸಂಪರ್ಕಗಳು. ನೈಜ ಸಂಬಂಧಕ್ಕೆ ಸಿದ್ಧರಾಗಿರುವವರಿಗೆ ಆಧುನಿಕ, ಎಲ್ಲರನ್ನೂ ಒಳಗೊಂಡ ವಿವಾಹ ಅನುಭವ.",
  "A new kind of matrimony": "ಹೊಸ ರೀತಿಯ ವಿವಾಹ ವೇದಿಕೆ",
  "Where hearts meet, lives belong.": "ಮನಗಳು ಸೇರುವ, ಬದುಕುಗಳು ಬೆಸೆಯುವ ತಾಣ.",
  "Find someone who understands": "ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವವರನ್ನು ಹುಡುಕಿ",
  "your journey.": "ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು.",
  "A trusted and inclusive matrimony platform designed for meaningful relationships — with privacy, intention and a little more humanity.": "ಗೌಪ್ಯತೆ, ಉದ್ದೇಶ ಮತ್ತು ಮಾನವೀಯತೆಯೊಂದಿಗೆ ಅರ್ಥಪೂರ್ಣ ಸಂಬಂಧಗಳಿಗಾಗಿ ನಿರ್ಮಿಸಲಾದ ವಿಶ್ವಾಸಾರ್ಹ, ಎಲ್ಲರನ್ನೂ ಒಳಗೊಂಡ ವಿವಾಹ ವೇದಿಕೆ.",
  "Create your profile": "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ರಚಿಸಿ",
  "Create a profile": "ಪ್ರೊಫೈಲ್ ರಚಿಸಿ",
  "Explore matches": "ಹೊಂದಾಣಿಕೆಗಳನ್ನು ನೋಡಿ",
  "Verified profiles · Privacy-first by design": "ಪರಿಶೀಲಿತ ಪ್ರೊಫೈಲ್‌ಗಳು · ವಿನ್ಯಾಸದಲ್ಲೇ ಗೌಪ್ಯತೆ ಮೊದಲು",
  "Identity verified": "ಗುರುತು ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
  "Active now": "ಈಗ ಸಕ್ರಿಯ",
  "92% preference match": "92% ಆದ್ಯತೆ ಹೊಂದಾಣಿಕೆ",
  "Verified profiles": "ಪರಿಶೀಲಿತ ಪ್ರೊಫೈಲ್‌ಗಳು",
  "Identity-led trust": "ಗುರುತಿನ ಆಧಾರದ ವಿಶ್ವಾಸ",
  "Privacy protected": "ಗೌಪ್ಯತೆ ರಕ್ಷಿತ",
  "You choose what to share": "ಏನು ಹಂಚಿಕೊಳ್ಳಬೇಕು ಎಂಬುದು ನಿಮ್ಮ ಆಯ್ಕೆ",
  "Inclusive by design": "ಎಲ್ಲರನ್ನೂ ಒಳಗೊಂಡ ವಿನ್ಯಾಸ",
  "Every journey belongs": "ಪ್ರತಿಯೊಂದು ಪ್ರಯಾಣವೂ ಮುಖ್ಯ",
  "Secure communication": "ಸುರಕ್ಷಿತ ಸಂವಹನ",
  "Connect at your pace": "ನಿಮ್ಮ ವೇಗದಲ್ಲಿ ಸಂಪರ್ಕಿಸಿ",
  "A considered beginning": "ಚಿಂತನಶೀಲ ಆರಂಭ",
  "Built for the relationship you’re ready for.": "ನೀವು ಸಿದ್ಧವಾಗಿರುವ ಸಂಬಂಧಕ್ಕಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ.",
  "Everything on Advaita is designed to make meeting someone feel more thoughtful — from your first preference to your first conversation.": "ನಿಮ್ಮ ಮೊದಲ ಆದ್ಯತೆಯಿಂದ ಮೊದಲ ಸಂಭಾಷಣೆಯವರೆಗೆ, ಭೇಟಿಯಾಗುವ ಅನುಭವವನ್ನು ಹೆಚ್ಚು ಅರ್ಥಪೂರ್ಣವಾಗಿಸಲು Advaitaಯ ಪ್ರತಿಯೊಂದು ಅಂಶವನ್ನು ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ.",
  "Share the parts of your life that matter to you.": "ನಿಮಗೆ ಮುಖ್ಯವಾದ ಜೀವನದ ಭಾಗಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಿ.",
  "Tell us what a meaningful fit looks like.": "ಅರ್ಥಪೂರ್ಣ ಹೊಂದಾಣಿಕೆ ಹೇಗಿರಬೇಕು ಎಂದು ತಿಳಿಸಿ.",
  "Build confidence with a trusted profile.": "ವಿಶ್ವಾಸಾರ್ಹ ಪ್ರೊಫೈಲ್‌ನೊಂದಿಗೆ ಆತ್ಮವಿಶ್ವಾಸ ಬೆಳೆಸಿಕೊಳ್ಳಿ.",
  "Explore people aligned with your journey.": "ನಿಮ್ಮ ಪ್ರಯಾಣಕ್ಕೆ ಹೊಂದುವ ಜನರನ್ನು ಅನ್ವೇಷಿಸಿ.",
  "Take the next step on your terms.": "ನಿಮ್ಮ ನಿಯಮಗಳಂತೆ ಮುಂದಿನ ಹೆಜ್ಜೆ ಇಡಿ.",
  "Trust is personal": "ವಿಶ್ವಾಸ ವೈಯಕ್ತಿಕ",
  "Thoughtful tools for a more human search.": "ಹೆಚ್ಚು ಮಾನವೀಯ ಹುಡುಕಾಟಕ್ಕಾಗಿ ಚಿಂತನಶೀಲ ಸಾಧನಗಳು.",
  "Controlled photo access": "ನಿಯಂತ್ರಿತ ಫೋಟೋ ಪ್ರವೇಶ",
  "Keep private photos protected and share them only when it feels right.": "ಖಾಸಗಿ ಫೋಟೋಗಳನ್ನು ಸುರಕ್ಷಿತವಾಗಿರಿಸಿ; ಸರಿಯೆನಿಸಿದಾಗ ಮಾತ್ರ ಹಂಚಿಕೊಳ್ಳಿ.",
  "Preference matching": "ಆದ್ಯತೆ ಹೊಂದಾಣಿಕೆ",
  "See why a profile fits based on the preferences you chose.": "ನೀವು ಆಯ್ಕೆ ಮಾಡಿದ ಆದ್ಯತೆಗಳ ಆಧಾರದ ಮೇಲೆ ಪ್ರೊಫೈಲ್ ಏಕೆ ಹೊಂದಿಕೊಳ್ಳುತ್ತದೆ ನೋಡಿ.",
  "Real-time visibility": "ನೈಜ-ಸಮಯದ ಗೋಚರತೆ",
  "Know when someone is active, while staying in control of your own presence.": "ನಿಮ್ಮ ಗೋಚರತೆಯ ನಿಯಂತ್ರಣವನ್ನು ಉಳಿಸಿಕೊಂಡೇ ಯಾರು ಸಕ್ರಿಯರಾಗಿದ್ದಾರೆ ಎಂದು ತಿಳಿಯಿರಿ.",
  "A safety-first space": "ಸುರಕ್ಷತೆಗೆ ಮೊದಲ ಆದ್ಯತೆ",
  "Clear reporting, blocking and guidance at every step.": "ಪ್ರತಿಯೊಂದು ಹಂತದಲ್ಲೂ ಸ್ಪಷ್ಟ ವರದಿ, ನಿರ್ಬಂಧ ಮತ್ತು ಮಾರ್ಗದರ್ಶನ.",
  "One platform · every journey": "ಒಂದು ವೇದಿಕೆ · ಪ್ರತಿಯೊಂದು ಪ್ರಯಾಣ",
  "Connection should have room for everyone.": "ಸಂಪರ್ಕದಲ್ಲಿ ಪ್ರತಿಯೊಬ್ಬರಿಗೂ ಸ್ಥಳ ಇರಬೇಕು.",
  "Advaita brings different life experiences into one respectful space — with the same care, privacy and possibility for every person.": "Advaita ವಿಭಿನ್ನ ಜೀವನಾನುಭವಗಳನ್ನು ಒಂದೇ ಗೌರವಯುತ ಸ್ಥಳಕ್ಕೆ ತರುತ್ತದೆ — ಪ್ರತಿಯೊಬ್ಬರಿಗೂ ಒಂದೇ ಕಾಳಜಿ, ಗೌಪ್ಯತೆ ಮತ್ತು ಸಾಧ್ಯತೆಯೊಂದಿಗೆ.",
  "Our inclusive promise": "ನಮ್ಮ ಒಳಗೊಳ್ಳುವಿಕೆಯ ಭರವಸೆ",
  "Physically Challenged / Locomotor Impairment": "ದೈಹಿಕ / ಚಲನ ಅಸಮರ್ಥತೆ",
  "Hearing & Speech Impaired": "ಶ್ರವಣ ಮತ್ತು ಮಾತಿನ ಅಸಮರ್ಥತೆ",
  "Vitiligo / Skin Condition Specific Profiles": "ವಿಟಿಲಿಗೋ / ಚರ್ಮದ ಸ್ಥಿತಿಗೆ ಸಂಬಂಧಿಸಿದ ಪ್ರೊಫೈಲ್‌ಗಳು",
  "General Public": "ಸಾಮಾನ್ಯ ವಿವಾಹ ಪ್ರೊಫೈಲ್‌ಗಳು",
  "(Divyangjan)": "(ದಿವ್ಯಾಂಗಜನ)",
  "(Deaf & Mute)": "(ಕಿವುಡರು ಮತ್ತು ಮೂಕರು)",
  "(Standard Matrimony)": "(ಸಾಮಾನ್ಯ ವಿವಾಹ)",
  "A respectful space where access, independence and partnership belong in the same conversation.": "ಪ್ರವೇಶ, ಸ್ವಾತಂತ್ರ್ಯ ಮತ್ತು ಸಂಗಾತಿತ್ವ ಒಂದೇ ಸಂಭಾಷಣೆಯಲ್ಲಿ ಸೇರಿರುವ ಗೌರವಯುತ ಸ್ಥಳ.",
  "Profiles and conversations that make room for different ways of communicating.": "ವಿಭಿನ್ನ ಸಂವಹನ ವಿಧಾನಗಳಿಗೆ ಅವಕಾಶ ನೀಡುವ ಪ್ರೊಫೈಲ್‌ಗಳು ಮತ್ತು ಸಂಭಾಷಣೆಗಳು.",
  "A community that sees the whole person first, with confidence and dignity.": "ಆತ್ಮವಿಶ್ವಾಸ ಮತ್ತು ಗೌರವದೊಂದಿಗೆ ವ್ಯಕ್ತಿಯನ್ನು ಮೊದಲು ಸಂಪೂರ್ಣವಾಗಿ ನೋಡುವ ಸಮುದಾಯ.",
  "A smaller, more considered shortlist": "ಚಿಕ್ಕದಾದ, ಹೆಚ್ಚು ಚಿಂತನಶೀಲ ಆಯ್ದ ಪಟ್ಟಿ",
  "Three new profiles with a clear reason they may fit your preferences. No endless feed required.": "ನಿಮ್ಮ ಆದ್ಯತೆಗಳಿಗೆ ಏಕೆ ಹೊಂದಬಹುದು ಎಂಬ ಸ್ಪಷ್ಟ ಕಾರಣವಿರುವ ಮೂರು ಹೊಸ ಪ್ರೊಫೈಲ್‌ಗಳು. ಅಂತ್ಯವಿಲ್ಲದ ಫೀಡ್ ಅಗತ್ಯವಿಲ್ಲ.",
  "Open today's picks": "ಇಂದಿನ ಆಯ್ಕೆಗಳನ್ನು ತೆರೆಯಿರಿ",
  "What makes a home feel like home to you?": "ಮನೆ ಎಂದರೆ ನಿಮಗೆ ಏನು ಅನಿಸುತ್ತದೆ?",
  "A gentle prompt helps people start with something more meaningful than hello.": "ಹಲೋ ಎನ್ನುವುದಕ್ಕಿಂತ ಹೆಚ್ಚು ಅರ್ಥಪೂರ್ಣವಾಗಿ ಆರಂಭಿಸಲು ಸರಳ ಪ್ರಶ್ನೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
  "Answer the prompt": "ಪ್ರಶ್ನೆಗೆ ಉತ್ತರಿಸಿ",
  "Your photos are still in your hands": "ನಿಮ್ಮ ಫೋಟೋಗಳು ಇನ್ನೂ ನಿಮ್ಮ ನಿಯಂತ್ರಣದಲ್ಲಿವೆ",
  "Review who can see your private photos and update access any time.": "ನಿಮ್ಮ ಖಾಸಗಿ ಫೋಟೋಗಳನ್ನು ಯಾರು ನೋಡಬಹುದು ಎಂಬುದನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಯಾವಾಗ ಬೇಕಾದರೂ ಪ್ರವೇಶ ಬದಲಾಯಿಸಿ.",
  "Review controls": "ನಿಯಂತ್ರಣಗಳನ್ನು ಪರಿಶೀಲಿಸಿ",
  "Meet with intention": "ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಭೇಟಿಯಾಗಿರಿ",
  "People, not profiles.": "ಪ್ರೊಫೈಲ್‌ಗಳಲ್ಲ, ಜನರು.",
  "Browse a small selection of verified members from our community.": "ನಮ್ಮ ಸಮುದಾಯದ ಪರಿಶೀಲಿತ ಸದಸ್ಯರ ಆಯ್ದ ಪ್ರೊಫೈಲ್‌ಗಳನ್ನು ನೋಡಿ.",
  "View all matches": "ಎಲ್ಲಾ ಹೊಂದಾಣಿಕೆಗಳನ್ನು ನೋಡಿ",
  "Your next chapter can start here": "ನಿಮ್ಮ ಮುಂದಿನ ಅಧ್ಯಾಯ ಇಲ್ಲಿಂದ ಆರಂಭವಾಗಬಹುದು",
  "Make space for something meaningful.": "ಅರ್ಥಪೂರ್ಣವಾದುದಕ್ಕೆ ಸ್ಥಳ ಮಾಡಿಕೊಳ್ಳಿ.",
  "Join a community that chooses trust, clarity and real connection.": "ವಿಶ್ವಾಸ, ಸ್ಪಷ್ಟತೆ ಮತ್ತು ನಿಜವಾದ ಸಂಪರ್ಕವನ್ನು ಆಯ್ಕೆ ಮಾಡುವ ಸಮುದಾಯಕ್ಕೆ ಸೇರಿ.",
  "See Advaita in motion": "Advaitaಯನ್ನು ಚಲನೆಯಲ್ಲೇ ನೋಡಿ",
  "A more human way to begin.": "ಆರಂಭಿಸಲು ಹೆಚ್ಚು ಮಾನವೀಯ ಮಾರ್ಗ.",
  "Discover a calmer matrimony experience built around trust, privacy and conversations that feel real.": "ವಿಶ್ವಾಸ, ಗೌಪ್ಯತೆ ಮತ್ತು ನೈಜವೆನಿಸುವ ಸಂಭಾಷಣೆಗಳ ಸುತ್ತ ನಿರ್ಮಿಸಲಾದ ಶಾಂತ ವಿವಾಹ ಅನುಭವವನ್ನು ಕಂಡುಕೊಳ್ಳಿ.",
  "Turn sound on": "ಧ್ವನಿ ಆನ್ ಮಾಡಿ",
  "Mute sound": "ಧ್ವನಿ ಮ್ಯೂಟ್ ಮಾಡಿ",
  "Product introduction": "ಉತ್ಪನ್ನ ಪರಿಚಯ",
  "Advaita Matrimony product introduction": "Advaita Matrimony ಉತ್ಪನ್ನ ಪರಿಚಯ",
  "Pause product video": "ಉತ್ಪನ್ನ ವೀಡಿಯೊ ವಿರಾಮಗೊಳಿಸಿ",
  "Play product video": "ಉತ್ಪನ್ನ ವೀಡಿಯೊ ಪ್ಲೇ ಮಾಡಿ",
  "Turn product video sound on": "ಉತ್ಪನ್ನ ವೀಡಿಯೊ ಧ್ವನಿ ಆನ್ ಮಾಡಿ",
  "Mute product video": "ಉತ್ಪನ್ನ ವೀಡಿಯೊ ಮ್ಯೂಟ್ ಮಾಡಿ",
  "Meet the person beyond the profile": "ಪ್ರೊಫೈಲ್‌ಗಿಂತಲೂ ಆ ವ್ಯಕ್ತಿಯನ್ನು ಭೇಟಿ ಮಾಡಿ",
  "fit": "ಹೊಂದಾಣಿಕೆ",
  "Clear context helps you decide who feels aligned without turning the search into a noisy social feed.": "ಹುಡುಕಾಟವನ್ನು ಗದ್ದಲದ ಸಾಮಾಜಿಕ ಫೀಡ್ ಆಗಿಸದೆ, ಯಾರು ಹೊಂದಿಕೆಯಾಗುತ್ತಾರೆ ಎಂದು ನಿರ್ಧರಿಸಲು ಸ್ಪಷ್ಟ ಹಿನ್ನೆಲೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
  "Photos and videos can be public, shared after connection, request-only or private.": "ಫೋಟೋಗಳು ಮತ್ತು ವೀಡಿಯೊಗಳು ಸಾರ್ವಜನಿಕವಾಗಿರಬಹುದು, ಸಂಪರ್ಕದ ನಂತರ ಹಂಚಿಕೊಳ್ಳಬಹುದು, ವಿನಂತಿಯ ಮೇರೆಗೆ ಮಾತ್ರ ಇರಬಹುದು ಅಥವಾ ಖಾಸಗಿಯಾಗಿರಬಹುದು.",
  "Every profile can answer one gentle prompt to make the first message easier.": "ಮೊದಲ ಸಂದೇಶವನ್ನು ಸುಲಭಗೊಳಿಸಲು ಪ್ರತಿಯೊಂದು ಪ್ರೊಫೈಲ್ ಕೂಡ ಒಂದು ಸರಳ ಪ್ರಶ್ನೆಗೆ ಉತ್ತರಿಸಬಹುದು.",
  "The strongest product loop is not endless scrolling. It is a useful next step, a clear privacy choice and one better conversation.": "ಉತ್ತಮ ಉತ್ಪನ್ನ ಅನುಭವವೆಂದರೆ ಅಂತ್ಯವಿಲ್ಲದ ಸ್ಕ್ರೋಲಿಂಗ್ ಅಲ್ಲ. ಅದು ಉಪಯುಕ್ತ ಮುಂದಿನ ಹೆಜ್ಜೆ, ಸ್ಪಷ್ಟ ಗೌಪ್ಯತಾ ಆಯ್ಕೆ ಮತ್ತು ಇನ್ನಷ್ಟು ಉತ್ತಮ ಸಂಭಾಷಣೆ.",
  "Featured introduction": "ವೈಶಿಷ್ಟ್ಯಪೂರ್ಣ ಪರಿಚಯ",
  "Some connections begin with a small moment. Watch a short introduction, then decide if you want to know more.": "ಕೆಲವು ಸಂಪರ್ಕಗಳು ಸಣ್ಣ ಕ್ಷಣದಿಂದ ಆರಂಭವಾಗುತ್ತವೆ. ಚಿಕ್ಕ ಪರಿಚಯವನ್ನು ನೋಡಿ, ನಂತರ ಇನ್ನಷ್ಟು ತಿಳಿದುಕೊಳ್ಳಬೇಕೇ ಎಂದು ನಿರ್ಧರಿಸಿ.",
  "Shared with consent · private media stays protected": "ಸಮ್ಮತಿಯೊಂದಿಗೆ ಹಂಚಲಾಗಿದೆ · ಖಾಸಗಿ ಮಾಧ್ಯಮ ಸುರಕ್ಷಿತವಾಗಿರುತ್ತದೆ",
  "Privacy-first by design": "ವಿನ್ಯಾಸದಲ್ಲೇ ಗೌಪ್ಯತೆ ಮೊದಲು",
  "See the person behind the profile": "ಪ್ರೊಫೈಲ್ ಹಿಂದಿರುವ ವ್ಯಕ್ತಿಯನ್ನು ನೋಡಿ",
  "Small details make a better first impression.": "ಸಣ್ಣ ವಿವರಗಳು ಉತ್ತಮ ಮೊದಲ ಅಭಿಪ್ರಾಯವನ್ನು ರೂಪಿಸುತ್ತವೆ.",
  "Move through a few thoughtful profiles, understand what makes each person distinct, and connect only when it feels right.": "ಕೆಲವು ಚಿಂತನಶೀಲ ಪ್ರೊಫೈಲ್‌ಗಳನ್ನು ನೋಡಿ, ಪ್ರತಿಯೊಬ್ಬರ ವೈಶಿಷ್ಟ್ಯವನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ ಮತ್ತು ಸರಿಯೆನಿಸಿದಾಗ ಮಾತ್ರ ಸಂಪರ್ಕಿಸಿ.",
  "Consent-led profiles": "ಸಮ್ಮತಿ ಆಧಾರಿತ ಪ್ರೊಫೈಲ್‌ಗಳು",
  "Profiles with intention": "ಉದ್ದೇಶಪೂರ್ವಕ ಪ್ರೊಫೈಲ್‌ಗಳು",
  "Private by default": "ಡೀಫಾಲ್ಟ್ ಆಗಿ ಖಾಸಗಿ",
  "Conversation starters": "ಸಂಭಾಷಣೆ ಆರಂಭಿಸುವ ಸೂಚನೆಗಳು",
  "A reason to come back": "ಮತ್ತೆ ಬರಲು ಒಂದು ಕಾರಣ",
  "Retention without pressure.": "ಒತ್ತಡವಿಲ್ಲದ ನಿರಂತರ ಅನುಭವ.",
  "No noisy streaks. No manipulative countdowns.": "ಗದ್ದಲದ ಸ್ಟ್ರೀಕ್‌ಗಳಿಲ್ಲ. ಒತ್ತಡದ ಕೌಂಟ್‌ಡೌನ್‌ಗಳಿಲ್ಲ.",
  "Your daily 3": "ನಿಮ್ಮ ದೈನಂದಿನ 3",
  "Conversation prompt": "ಸಂಭಾಷಣೆಯ ಸೂಚನೆ",
  "Privacy check-in": "ಗೌಪ್ಯತಾ ಪರಿಶೀಲನೆ",
  "Open profile": "ಪ್ರೊಫೈಲ್ ತೆರೆಯಿರಿ",
  "Save for later": "ನಂತರಕ್ಕಾಗಿ ಉಳಿಸಿ",
  "Saved": "ಉಳಿಸಲಾಗಿದೆ",
  "Interest Sent": "ಆಸಕ್ತಿ ಕಳುಹಿಸಲಾಗಿದೆ",
  "Send Interest": "ಆಸಕ್ತಿ ಕಳುಹಿಸಿ",
  "Verified": "ಪರಿಶೀಲಿತ",
  "Premium": "ಪ್ರೀಮಿಯಂ",
  "Profile photo": "ಪ್ರೊಫೈಲ್ ಫೋಟೋ",
  "Intro video": "ಪರಿಚಯ ವೀಡಿಯೊ",
  "Request to view": "ನೋಡಲು ವಿನಂತಿಸಿ",
  "Shared after connecting": "ಸಂಪರ್ಕದ ನಂತರ ಹಂಚಿಕೊಳ್ಳಲಾಗುತ್ತದೆ",
  "Loading Advaita Matrimony": "Advaita Matrimony ಲೋಡ್ ಆಗುತ್ತಿದೆ",
  "Come as you are": "ನೀವು ಹೇಗಿದ್ದೀರೋ ಹಾಗೆಯೇ ಬನ್ನಿ",
  "A more thoughtful way to meet": "ಭೇಟಿಯಾಗಲು ಹೆಚ್ಚು ಚಿಂತನಶೀಲ ಮಾರ್ಗ",
  "Back to home": "ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ",
  "Welcome back": "ಮತ್ತೆ ಸ್ವಾಗತ",
  "Mobile number": "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
  "Email address": "ಇಮೇಲ್ ವಿಳಾಸ",
  "Continue": "ಮುಂದುವರಿಸಿ",
  "Use demo account": "ಡೆಮೋ ಖಾತೆ ಬಳಸಿ",
  "Account": "ಖಾತೆ",
  "About you": "ನಿಮ್ಮ ಬಗ್ಗೆ",
  "Location": "ಸ್ಥಳ",
  "Education": "ಶಿಕ್ಷಣ",
  "Career": "ವೃತ್ತಿ",
  "Family": "ಕುಟುಂಬ",
  "Lifestyle": "ಜೀವನಶೈಲಿ",
  "Inclusion": "ಒಳಗೊಳ್ಳುವಿಕೆ",
  "Preferences": "ಆದ್ಯತೆಗಳು",
  "Photos": "ಫೋಟೋಗಳು",
  "Preview": "ಮುನ್ನೋಟ",
  "Your profile": "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್",
  "A little more about you.": "ನಿಮ್ಮ ಬಗ್ಗೆ ಇನ್ನಷ್ಟು ತಿಳಿಸಿ.",
  "Saved automatically": "ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಉಳಿಸಲಾಗಿದೆ",
  "Save & exit": "ಉಳಿಸಿ ಮತ್ತು ನಿರ್ಗಮಿಸಿ",
  "Back": "ಹಿಂದೆ",
  "Preview profile": "ಪ್ರೊಫೈಲ್ ಮುನ್ನೋಟ",
  "This helps us introduce you to people who are more likely to understand your journey.": "ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವ ಸಾಧ್ಯತೆ ಇರುವ ಜನರಿಗೆ ನಿಮ್ಮನ್ನು ಪರಿಚಯಿಸಲು ಇದು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
  "Go to my space": "ನನ್ನ ಸ್ಥಳಕ್ಕೆ ಹೋಗಿ",
  "Your profile is ready to shine.": "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಹೊಳೆಯಲು ಸಿದ್ಧವಾಗಿದೆ.",
  "You’re on your way": "ನೀವು ಸರಿಯಾದ ದಾರಿಯಲ್ಲಿದ್ದೀರಿ",
  "Recommended for you": "ನಿಮಗಾಗಿ ಶಿಫಾರಸುಗಳು",
  "See all": "ಎಲ್ಲವನ್ನೂ ನೋಡಿ",
  "Your activity": "ನಿಮ್ಮ ಚಟುವಟಿಕೆ",
  "How Advaita works": "Advaita ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
  "A small daily ritual": "ಒಂದು ಸಣ್ಣ ದೈನಂದಿನ ಅಭ್ಯಾಸ",
  "Good morning, Ananya": "ಶುಭೋದಯ, ಅನನ್ಯಾ",
  "Your space is taking shape": "ನಿಮ್ಮ ಸ್ಥಳ ರೂಪ ಪಡೆಯುತ್ತಿದೆ",
  "Your matches are getting better.": "ನಿಮ್ಮ ಹೊಂದಾಣಿಕೆಗಳು ಉತ್ತಮವಾಗುತ್ತಿವೆ.",
  "Profile strength": "ಪ್ರೊಫೈಲ್ ಬಲ",
  "Improve profile": "ಪ್ರೊಫೈಲ್ ಸುಧಾರಿಸಿ",
  "Discover": "ಅನ್ವೇಷಿಸಿ",
  "Filters": "ಫಿಲ್ಟರ್‌ಗಳು",
  "Verified only": "ಪರಿಶೀಲಿತ ಮಾತ್ರ",
  "Reset": "ಮರುಹೊಂದಿಸಿ",
  "Save search": "ಹುಡುಕಾಟ ಉಳಿಸಿ",
  "Matches": "ಹೊಂದಾಣಿಕೆಗಳು",
  "Interests": "ಆಸಕ್ತಿಗಳು",
  "Shortlisted": "ಆಯ್ಕೆಪಟ್ಟಿ",
  "Messages": "ಸಂದೇಶಗಳು",
  "Notifications": "ಅಧಿಸೂಚನೆಗಳು",
  "Mark all as read": "ಎಲ್ಲವನ್ನೂ ಓದಿದಂತೆ ಗುರುತಿಸಿ",
  "Settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
  "Language": "ಭಾಷೆ",
  "English (India)": "ಇಂಗ್ಲಿಷ್ (ಭಾರತ)",
  "ಕನ್ನಡ": "ಕನ್ನಡ",
  "My profile": "ನನ್ನ ಪ್ರೊಫೈಲ್",
  "Safety center": "ಸುರಕ್ಷತಾ ಕೇಂದ್ರ",
  "Account & security": "ಖಾತೆ ಮತ್ತು ಭದ್ರತೆ",
  "Privacy & photo controls": "ಗೌಪ್ಯತೆ ಮತ್ತು ಫೋಟೋ ನಿಯಂತ್ರಣಗಳು",
  "Notification preferences": "ಅಧಿಸೂಚನೆ ಆದ್ಯತೆಗಳು",
  "Blocked members": "ನಿರ್ಬಂಧಿತ ಸದಸ್ಯರು",
  "Explore": "ಅನ್ವೇಷಿಸಿ",
  "About us": "ನಮ್ಮ ಬಗ್ಗೆ",
  "Trust & safety": "ವಿಶ್ವಾಸ ಮತ್ತು ಸುರಕ್ಷತೆ",
  "Privacy policy": "ಗೌಪ್ಯತಾ ನೀತಿ",
  "Terms of use": "ಬಳಕೆಯ ನಿಯಮಗಳು",
  "Need help?": "ಸಹಾಯ ಬೇಕೇ?",
  "FAQs": "ಪದೇಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು",
  "Contact support": "ಬೆಂಬಲ ಸಂಪರ್ಕಿಸಿ",
  "Member login": "ಸದಸ್ಯ ಲಾಗಿನ್",
  "Preference-led discovery": "ಆದ್ಯತೆ ಆಧಾರಿತ ಹುಡುಕಾಟ",
  "Verified by design": "ವಿನ್ಯಾಸದಲ್ಲೇ ಪರಿಶೀಲನೆ",
  "Privacy is a feature": "ಗೌಪ್ಯತೆಯೇ ಒಂದು ವೈಶಿಷ್ಟ್ಯ",
  "A human pace": "ಮಾನವೀಯ ವೇಗ",
  "Warm, not noisy": "ಬೆಚ್ಚಗಿನ ಅನುಭವ, ಗದ್ದಲವಿಲ್ಲ",
  "Technology with intent": "ಉದ್ದೇಶಪೂರ್ವಕ ತಂತ್ರಜ್ಞಾನ",
  "Inclusive at the core": "ಮೂಲದಲ್ಲೇ ಒಳಗೊಳ್ಳುವಿಕೆ",
  "Free": "ಉಚಿತ",
  "Premium Plus": "ಪ್ರೀಮಿಯಂ ಪ್ಲಸ್",
  "Most chosen": "ಹೆಚ್ಚು ಆಯ್ಕೆ ಮಾಡಲ್ಪಟ್ಟದ್ದು",
  "Choose Free": "ಉಚಿತವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "Choose Premium": "ಪ್ರೀಮಿಯಂ ಆಯ್ಕೆಮಾಡಿ",
  "Choose Premium Plus": "ಪ್ರೀಮಿಯಂ ಪ್ಲಸ್ ಆಯ್ಕೆಮಾಡಿ",
  "Your preference matches": "ನಿಮ್ಮ ಆದ್ಯತೆಗಳ ಹೊಂದಾಣಿಕೆಗಳು",
  "The right connection takes time.": "ಸರಿಯಾದ ಸಂಪರ್ಕಕ್ಕೆ ಸಮಯ ಬೇಕಾಗುತ್ತದೆ.",
  "As your profile grows, your recommendations will become more thoughtful and personal.": "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಬೆಳೆದಂತೆ, ನಿಮ್ಮ ಶಿಫಾರಸುಗಳು ಹೆಚ್ಚು ವೈಯಕ್ತಿಕ ಮತ್ತು ಚಿಂತನಶೀಲವಾಗುತ್ತವೆ.",
  "Thoughtful conversations": "ಚಿಂತನಶೀಲ ಸಂಭಾಷಣೆಗಳು",
  "Start with an interest.": "ಆಸಕ್ತಿಯಿಂದ ಆರಂಭಿಸಿ.",
  "Your conversations will appear here after you connect with someone.": "ಯಾರೊಂದಿಗಾದರೂ ಸಂಪರ್ಕಿಸಿದ ನಂತರ ನಿಮ್ಮ ಸಂಭಾಷಣೆಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.",
  "Today's thoughtful picks": "ಇಂದಿನ ಚಿಂತನಶೀಲ ಆಯ್ಕೆಗಳು",
  "People with intention": "ಉದ್ದೇಶಪೂರ್ವಕ ಜನರು",
  "Quick filters": "ತ್ವರಿತ ಫಿಲ್ಟರ್‌ಗಳು",
  "Age, location, education and privacy preferences can be expanded here.": "ವಯಸ್ಸು, ಸ್ಥಳ, ಶಿಕ್ಷಣ ಮತ್ತು ಗೌಪ್ಯತಾ ಆದ್ಯತೆಗಳನ್ನು ಇಲ್ಲಿ ವಿಸ್ತರಿಸಬಹುದು.",
  "Done": "ಮುಗಿದಿದೆ",
  "All profiles": "ಎಲ್ಲಾ ಪ್ರೊಫೈಲ್‌ಗಳು",
  "Bengaluru + nearby": "ಬೆಂಗಳೂರು + ಸುತ್ತಮುತ್ತ",
  "A LITTLE MORE ABOUT THEM": "ಅವರ ಬಗ್ಗೆ ಇನ್ನಷ್ಟು",
  "A little more about them": "ಅವರ ಬಗ್ಗೆ ಇನ್ನಷ್ಟು",
  "Profile note": "ಪ್ರೊಫೈಲ್ ಟಿಪ್ಪಣಿ",
  "We’ll show you a different profile": "ನಾವು ನಿಮಗೆ ಬೇರೆ ಪ್ರೊಫೈಲ್ ತೋರಿಸುತ್ತೇವೆ",
  "Pass this profile": "ಈ ಪ್ರೊಫೈಲ್ ಬಿಟ್ಟುಹೋಗಿ",
  "Shortlist this profile": "ಈ ಪ್ರೊಫೈಲ್ ಅನ್ನು ಆಯ್ಕೆಪಟ್ಟಿಗೆ ಸೇರಿಸಿ",
  "Close navigation": "ನ್ಯಾವಿಗೇಶನ್ ಮುಚ್ಚಿ",
  "Close navigation overlay": "ನ್ಯಾವಿಗೇಶನ್ ಓವರ್‌ಲೇ ಮುಚ್ಚಿ",
  "Primary navigation": "ಮುಖ್ಯ ನ್ಯಾವಿಗೇಶನ್",
  "Open navigation": "ನ್ಯಾವಿಗೇಶನ್ ತೆರೆಯಿರಿ",
  "Open menu": "ಮೆನು ತೆರೆಯಿರಿ",
  "Close menu": "ಮೆನು ಮುಚ್ಚಿ",
  "Search": "ಹುಡುಕಿ",
  "Send interest": "ಆಸಕ್ತಿ ಕಳುಹಿಸಿ",
  "Pass profile": "ಪ್ರೊಫೈಲ್ ಬಿಟ್ಟುಹೋಗಿ",
  "Shortlist profile": "ಪ್ರೊಫೈಲ್ ಅನ್ನು ಆಯ್ಕೆಪಟ್ಟಿಗೆ ಸೇರಿಸಿ",
  "Swipe left to pass · right to send interest · tap actions for control": "ಬಿಟ್ಟುಹೋಗಲು ಎಡಕ್ಕೆ · ಆಸಕ್ತಿ ಕಳುಹಿಸಲು ಬಲಕ್ಕೆ · ನಿಯಂತ್ರಣಕ್ಕಾಗಿ ಕ್ರಿಯೆಗಳನ್ನು ಟ್ಯಾಪ್ ಮಾಡಿ",
  "Back to discover": "ಅನ್ವೇಷಣೆಗೆ ಹಿಂತಿರುಗಿ",
  "A PREFERENCE MATCH": "ಆದ್ಯತೆ ಹೊಂದಾಣಿಕೆ",
  "Preference match": "ಆದ್ಯತೆ ಹೊಂದಾಣಿಕೆ",
  "Privacy controlled": "ಗೌಪ್ಯತೆ ನಿಯಂತ್ರಿತ",
  "Request private photos": "ಖಾಸಗಿ ಫೋಟೋಗಳಿಗೆ ವಿನಂತಿಸಿ",
  "Photo request sent": "ಫೋಟೋ ವಿನಂತಿ ಕಳುಹಿಸಲಾಗಿದೆ",
  "You decide what to share and when.": "ಏನು ಮತ್ತು ಯಾವಾಗ ಹಂಚಿಕೊಳ್ಳಬೇಕು ಎಂಬುದು ನಿಮ್ಮ ಆಯ್ಕೆ.",
  "Every media item has its own privacy setting. No automatic sharing.": "ಪ್ರತಿಯೊಂದು ಮಾಧ್ಯಮಕ್ಕೂ ತನ್ನದೇ ಗೌಪ್ಯತಾ ಸೆಟ್ಟಿಂಗ್ ಇದೆ. ಸ್ವಯಂಚಾಲಿತ ಹಂಚಿಕೆ ಇಲ್ಲ.",
  "Message profile": "ಪ್ರೊಫೈಲ್‌ಗೆ ಸಂದೇಶ ಕಳುಹಿಸಿ",
  "Open discovery filters": "ಹುಡುಕಾಟ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆರೆಯಿರಿ",
  "Open profile and notifications": "ಪ್ರೊಫೈಲ್ ಮತ್ತು ಅಧಿಸೂಚನೆಗಳನ್ನು ತೆರೆಯಿರಿ",
  "Made with care for meaningful beginnings.": "ಅರ್ಥಪೂರ್ಣ ಆರಂಭಗಳಿಗಾಗಿ ಕಾಳಜಿಯಿಂದ ನಿರ್ಮಿಸಲಾಗಿದೆ.",
  "5,000+ verified members": "5,000+ ಪರಿಶೀಲಿತ ಸದಸ್ಯರು",
  "meaningful introductions every week": "ಪ್ರತಿ ವಾರ ಅರ್ಥಪೂರ್ಣ ಪರಿಚಯಗಳು",
  "Verified members": "ಪರಿಶೀಲಿತ ಸದಸ್ಯರು",
  "Happy matches": "ಸಂತೋಷದ ಹೊಂದಾಣಿಕೆಗಳು",
  "Cities across India": "ಭಾರತದಾದ್ಯಂತ ನಗರಗಳು",
  "Average member rating": "ಸರಾಸರಿ ಸದಸ್ಯ ರೇಟಿಂಗ್",
  "Real stories": "ನಿಜವಾದ ಕಥೆಗಳು",
  "Journeys that began here.": "ಇಲ್ಲಿ ಆರಂಭವಾದ ಪ್ರಯಾಣಗಳು.",
  "Thousands have found a meaningful partner on Advaita. Here are a few of them.": "ಸಾವಿರಾರು ಮಂದಿ Advaitaಯಲ್ಲಿ ಅರ್ಥಪೂರ್ಣ ಸಂಗಾತಿಯನ್ನು ಕಂಡುಕೊಂಡಿದ್ದಾರೆ. ಅವರಲ್ಲಿ ಕೆಲವರು ಇಲ್ಲಿದ್ದಾರೆ.",
  "Married 2025 · Bengaluru": "2025ರಲ್ಲಿ ವಿವಾಹ · ಬೆಂಗಳೂರು",
  "Married 2025 · Chennai": "2025ರಲ್ಲಿ ವಿವಾಹ · ಚೆನ್ನೈ",
  "Married 2024 · Hyderabad": "2024ರಲ್ಲಿ ವಿವಾಹ · ಹೈದರಾಬಾದ್",
  "We connected over a love for design and long walks. The first conversation felt easy, and the rest just followed.": "ವಿನ್ಯಾಸ ಮತ್ತು ದೀರ್ಘ ನಡಿಗೆಗಳ ಪ್ರೀತಿಯಿಂದ ನಾವು ಸಂಪರ್ಕಗೊಂಡೆವು. ಮೊದಲ ಸಂಭಾಷಣೆ ಸುಲಭವಾಗಿತ್ತು, ಉಳಿದದ್ದು ತಾನಾಗಿಯೇ ಸಾಗಿತು.",
  "Being truly heard mattered most to us. Here that came first — everything meaningful grew from it.": "ನಿಜವಾಗಿ ಆಲಿಸಲ್ಪಡುವುದು ನಮಗೆ ಅತ್ಯಂತ ಮುಖ್ಯವಾಗಿತ್ತು. ಇಲ್ಲಿ ಅದು ಮೊದಲು ಬಂತು — ಅರ್ಥಪೂರ್ಣವಾದ ಎಲ್ಲವೂ ಅದರಿಂದ ಬೆಳೆಯಿತು.",
  "No endless scrolling — just a few thoughtful introductions. One of them quietly changed my life.": "ಅಂತ್ಯವಿಲ್ಲದ ಸ್ಕ್ರೋಲಿಂಗ್ ಇಲ್ಲ — ಕೆಲವು ಚಿಂತನಶೀಲ ಪರಿಚಯಗಳಷ್ಟೇ. ಅವುಗಳಲ್ಲಿ ಒಂದು ನನ್ನ ಬದುಕನ್ನು ಶಾಂತವಾಗಿ ಬದಲಾಯಿಸಿತು.",
  "Introducing Advaita Matrimony": "Advaita Matrimony ಪರಿಚಯ",
  "Register today": "ಇಂದೇ ನೋಂದಾಯಿಸಿ",
  "Harmony · Unity · Love · For a Lifetime": "ಸಾಮರಸ್ಯ · ಏಕತೆ · ಪ್ರೀತಿ · ಜೀವಮಾನ ಪೂರ್ತಿ",
};

const reverseTranslations = Object.fromEntries(Object.entries(uiTranslations).map(([english, kannada]) => [kannada, english]));

export function translateText(value: string, language: SupportedLanguage) {
  const exact = language === "kn" ? uiTranslations[value] : reverseTranslations[value];
  if (exact) return exact;
  const interest = value.match(/^Interest sent to (.+)$/);
  if (language === "kn" && interest) return `${interest[1]} ಅವರಿಗೆ ಆಸಕ್ತಿ ಕಳುಹಿಸಲಾಗಿದೆ`;
  if (language === "en" && value.endsWith(" ಅವರಿಗೆ ಆಸಕ್ತಿ ಕಳುಹಿಸಲಾಗಿದೆ")) return `Interest sent to ${value.replace(" ಅವರಿಗೆ ಆಸಕ್ತಿ ಕಳುಹಿಸಲಾಗಿದೆ", "")}`;
  const saved = value.match(/^(.+) saved to your shortlist$/);
  if (language === "kn" && saved) return `${saved[1]} ಅವರನ್ನು ಆಯ್ಕೆಪಟ್ಟಿಗೆ ಸೇರಿಸಲಾಗಿದೆ`;
  if (language === "en" && value.endsWith(" ಅವರನ್ನು ಆಯ್ಕೆಪಟ್ಟಿಗೆ ಸೇರಿಸಲಾಗಿದೆ")) return `${value.replace(" ಅವರನ್ನು ಆಯ್ಕೆಪಟ್ಟಿಗೆ ಸೇರಿಸಲಾಗಿದೆ", "")} saved to your shortlist`;
  const openedProfile = value.match(/^Open (.+)'s profile$/);
  if (language === "kn" && openedProfile) return `${openedProfile[1]} ಅವರ ಪ್ರೊಫೈಲ್ ತೆರೆಯಿರಿ`;
  if (language === "en" && value.endsWith(" ಅವರ ಪ್ರೊಫೈಲ್ ತೆರೆಯಿರಿ")) return `Open ${value.replace(" ಅವರ ಪ್ರೊಫೈಲ್ ತೆರೆಯಿರಿ", "")}'s profile`;
  const shortlistAction = value.match(/^(Add|Remove) (.+) (to|from) shortlist$/);
  if (language === "kn" && shortlistAction) return shortlistAction[1] === "Add" ? `${shortlistAction[2]} ಅವರನ್ನು ಆಯ್ಕೆಪಟ್ಟಿಗೆ ಸೇರಿಸಿ` : `${shortlistAction[2]} ಅವರನ್ನು ಆಯ್ಕೆಪಟ್ಟಿಯಿಂದ ತೆಗೆದುಹಾಕಿ`;
  const count = value.match(/^(\d+) new compatible profiles were added today$/);
  if (language === "kn" && count) return `ಇಂದು ${count[1]} ಹೊಸ ಹೊಂದಾಣಿಕೆಯ ಪ್ರೊಫೈಲ್‌ಗಳನ್ನು ಸೇರಿಸಲಾಗಿದೆ`;
  const kannadaCount = value.match(/^ಇಂದು (\d+) ಹೊಸ ಹೊಂದಾಣಿಕೆಯ ಪ್ರೊಫೈಲ್‌ಗಳನ್ನು ಸೇರಿಸಲಾಗಿದೆ$/);
  if (language === "en" && kannadaCount) return `${kannadaCount[1]} new compatible profiles were added today`;
  return value;
}
