"use client";

import { useMemo, useState } from "react";
import { Filter, Heart, MapPin, RotateCcw, Search, SlidersHorizontal, Star, X } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { ProfileCard, Toast } from "@/components/ui";
import { profiles } from "@/lib/mock-data";

export default function Discover() { const [query,setQuery]=useState(""); const [verified,setVerified]=useState(false); const [toast,setToast]=useState(""); const filtered=useMemo(()=>profiles.filter(p=>(!query || `${p.name} ${p.city} ${p.profession}`.toLowerCase().includes(query.toLowerCase())) && (!verified || p.verified)),[query,verified]); return <AppShell active="Discover"><div className="side-card" style={{ marginBottom:24, display:"flex", gap:12, alignItems:"center", padding:12 }}><Search size={18} color="var(--ink-soft)" /><input className="form-input" style={{ border:0, minHeight:36, padding:0, boxShadow:"none" }} placeholder="Search by name, city or profession" value={query} onChange={e=>setQuery(e.target.value)} /><button className="btn btn-soft" style={{ minHeight:38 }}><SlidersHorizontal size={15} /> Filters</button></div><div style={{ display:"flex", gap:8, flexWrap:"wrap", marginBottom:24 }}><button className={`pill ${verified ? "pill-verified" : "pill-quiet"}`} onClick={()=>setVerified(!verified)}><Filter size={13} /> Verified only {verified && <X size={12} />}</button><span className="pill pill-quiet"><MapPin size={13} /> Bengaluru + nearby</span><span className="pill pill-quiet">Age 26–34</span><button className="pill pill-quiet" style={{ border:0 }} onClick={()=>{setQuery("");setVerified(false)}}><RotateCcw size={12} /> Reset</button></div><div className="content-heading"><div><h2>{filtered.length} compatible profiles</h2><p className="muted" style={{ margin:"5px 0 0", fontSize:12 }}>Based on your preferences, updated today.</p></div><button className="btn btn-ghost" style={{ minHeight:38, fontSize:12 }}><Star size={14} /> Save search</button></div>{filtered.length ? <div className="profile-grid">{filtered.map(profile=><div key={profile.id} onClick={()=>setToast(`${profile.name} added to your discovery list`)}><ProfileCard profile={profile}/></div>)}</div> : <div style={{ marginTop:20, textAlign:"center", padding:60 }}><Heart size={25} color="var(--plum)" /><h3>No profiles match yet</h3><p className="muted">Try widening one of your preferences.</p></div>}{toast && <Toast message={toast} onClose={()=>setToast("")} />}</AppShell>; }
